### ISSUE TITLE
Implement code coverage metrics on seneca repos

### ISSUE THREAD

**Issue by faceleg** [senecajs/contrib#35]
This can be helpful, especially when combined with #34 to force PR's to include tests, and to show new contributors where they might start helping - by writing more tests!

My bash file for doing this is:

```BASH
mkdir -p coverage
node_modules/.bin/istanbul cover --include-all-sources -x file_to_ignore.js node_modules/.bin/_mocha -- --timeout 15000 --recursive --reporter spec test/configure.js test/
node_modules/.bin/istanbul report html
node_modules/.bin/istanbul report text-summary > coverage/text-summary.txt
node_modules/.bin/coverage-average coverage/text-summary.txt --limit 95
```

This will also create a pretty HTML coverage site that can be browsed locally to give hints on where your testing is missing things.

Note this uses the `coverage-average` module that will `exit 1` if coverage falls below a given value.

```BASH
npm install --save-dev coverage-average istanbul
```

If the above bash lines describe your total test script, then any CI builds for code with coverage below the given threshold (95% in this case) will fail.

Commits (using #34) that add code such that coverage falls below the threshold will fail.

**Comment by mcdonnelldean** [comment]
@faceleg I have a couple of people I want to bring in on this one. Let me organise that before I give my thoughts.

**Comment by faceleg** [comment]
This is the "nuclear war" approach. 

Even just rigging the repo's test scripts to generate coverage reports is a big win.

Doing that opens you up to exporting coverage to CodeClimate, for example (https://codeclimate.com/ free for open source)

**Comment by mcdonnelldean** [comment]
@geek How are Hapi approaching this stuff?

**Comment by geek** [comment]
Lab has this built-in.  So you add either `-t 98` with what percent of coverage you expect or just do `-c` to force 100% :)

**Comment by faceleg** [comment]
This raises another question - what testing framework will be "the standard"?

**Comment by mcdonnelldean** [comment]
@faceleg We have chosen lab as our "blessed" test framework but ultimately each lead maintainer is free to do as they wish with their given repos. They generally stick with Lab though.

**Comment by geek** [comment]
@faceleg exactly what @mcdonnelldean said... For readability, I really prefer to use https://www.npmjs.com/package/code for the assertion library

**Comment by faceleg** [comment]
Jeez I wish I knew about `code` when I was deciding what assertion lib to use

**Comment by geek** [comment]
:) @faceleg chai with a consistent API

**Comment by faceleg** [comment]
Yeah and without the parenthesis lacking assertions

**Comment by mcdonnelldean** [comment]
@faceleg @geek Are we happy enough to close this?

**Comment by faceleg** [comment]
I'm ecstatic

**Comment by mcdonnelldean** [comment]
:dancer:
