### ISSUE TITLE
What versions of node to support?

### ISSUE THREAD

**Issue by faceleg** [senecajs/contrib#36]
Ran into an issue with the PR https://github.com/rjrodger/seneca-web/pull/23 where Promise is not defined in node 0.10.

It would be great if we had a list of node versions that seneca and the plugin ecosystem must support.

**Comment by mcdonnelldean** [comment]
@faceleg This is something we are working through. If you look over some of the plugins, especially store and transports you will see we are now listing these out in the README and .travis.yml. I also plan to have a catch up with @geek and @rjrodger about the 'blessed' range of versions. Once I get this I will add some documentation to this repo too :D

**Comment by geek** [comment]
I am under the assumption that we support node 0.10, 0.12, and 4.x.  Although, I do like the idea of a LTS version of seneca and an 4.x optimized version that can take advantage of some of the ES6 features.

**Comment by mcdonnelldean** [comment]
@geek We should have a round table on this.

**Comment by mcdonnelldean** [comment]
For now I am going to close this, right now support is `0.10, 0.12, 4.x`
