### ISSUE TITLE
Clean up teams

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/contrib#5]
We should probably clean up the teams sooner rather than later. I think we have too many right now. I think we need:

- core: full admin rights
- contributors: contrib rights
- writer's: ability to make pr's ?

@geek @rjrodger can we kick off a quick discussion on this.

**Comment by geek** [comment]
I think we only need core and contributors.  I created both of these teams.  Core people should be members of both.  Any project that is depended on by seneca will have core as the collaborators.  All other projects should have contributors set as the collaborators.

Thoughts?

**Comment by mcdonnelldean** [comment]
I'm all for as simple as possible, right now there are two many so the less the better :smile:

**Comment by mcdonnelldean** [comment]
@geek I'll leave this for you to close when it's done :+1:
